const { app, safeStorage } = require('electron')
const assert = require('node:assert/strict')
const { mkdtemp, mkdir, readFile, writeFile } = require('node:fs/promises')
const { tmpdir } = require('node:os')
const { join } = require('node:path')

app.on('window-all-closed', () => {})

async function main() {
  const directory = await mkdtemp(join(tmpdir(), 'luma-drive-qc-'))
  app.setPath('userData', directory)
  global.__LUMA_GOOGLE_CLIENT_ID__ = '123456-abc.apps.googleusercontent.com'
  const drive = await import('../src/main/drive.ts')
  assert.equal((await drive.driveStatus()).configured, true, 'A fresh build with public client ID needs no setup file')
  assert.equal(drive.tokenRequestParams({ client_id: 'synthetic', grant_type: 'refresh_token' }, null).has('client_secret'), false, 'Native-app token requests must work without a bundled secret')
  const jpeg = `data:image/jpeg;base64,${Buffer.from('synthetic test image').toString('base64')}`
  await assert.rejects(() => drive.configureDrive('not-a-google-client-id', 'synthetic-secret'))
  await drive.configureDrive('123456-abc.apps.googleusercontent.com', 'synthetic-secret')
  await drive.queueFrame({ sessionId: 'session-a', sessionName: 'Synthetic', frameId: 'frame-a', frameName: 'Frame A', finalImage: jpeg, photos: [{ id: 'photo-a', dataUrl: jpeg }, { id: 'photo-b', dataUrl: jpeg }] })
  let status = await drive.driveStatus()
  assert.equal(status.pending, 1)
  await drive.processQueue()
  status = await drive.driveStatus()
  assert.equal(status.pending, 1, 'Offline upload must remain queued')
  if (!safeStorage.isEncryptionAvailable()) { console.log('PASS offline queue; encrypted token storage unavailable, skipping API mock'); return }
  const root = join(directory, 'drive-sync')
  await mkdir(root, { recursive: true })
  await writeFile(join(root, 'token.bin'), safeStorage.encryptString(JSON.stringify({ access_token: 'synthetic', refresh_token: 'synthetic', expires_at: Date.now() + 3600_000 })))
  const calls = []
  let nextId = 0
  global.fetch = async (url, init = {}) => {
    const target = String(url)
    calls.push({ url: target, method: init.method ?? 'GET', body: init.body })
    const method = init.method ?? 'GET'
    if (method === 'GET' && target.includes('?q=')) return new Response(JSON.stringify({ files: nextId > 0 ? [{ id: 'created-1' }] : [] }), { status: 200, headers: { 'Content-Type': 'application/json' } })
    if (method === 'POST') return new Response(JSON.stringify({ id: `created-${++nextId}` }), { status: 200, headers: { 'Content-Type': 'application/json' } })
    if (method === 'PATCH') return new Response('{}', { status: 200, headers: { 'Content-Type': 'application/json' } })
    if (method === 'DELETE') return new Response(null, { status: 204 })
    throw new Error(`Unexpected Drive call: ${method} ${target}`)
  }
  await drive.processQueue()
  status = await drive.driveStatus()
  assert.equal(status.pending, 0, status.message)
  const first = await drive.frameLink('session-a', 'frame-a')
  assert.match(first.url, /^https:\/\/drive\.google\.com\/drive\/folders\/created-3$/)
  assert.equal(calls.filter(call => call.url.includes('/permissions')).length, 1, 'Only frame folder should receive public permission')
  assert.ok(!calls.some(call => call.url.includes('/created-2/permissions')), 'Session parent must stay private')
  const folderCalls = calls.filter(call => call.method === 'POST' && call.url.startsWith('https://www.googleapis.com/drive/v3/files?'))
  assert.equal(folderCalls.length, 3, 'Create one root, one session, one frame folder')
  assert.equal(JSON.parse(folderCalls[1].body).parents[0], 'created-1', 'Session must be nested under the root folder')
  assert.equal(JSON.parse(folderCalls[2].body).parents[0], 'created-2', 'Frame must be nested under its session')

  const initialFiles = JSON.parse(await readFile(join(root, 'state.json'), 'utf8')).sessions['session-a'].frames['frame-a'].files
  assert.deepEqual(Object.keys(initialFiles).sort(), ['final', 'photo-a', 'photo-b'])
  await drive.queueFrame({ sessionId: 'session-a', sessionName: 'Synthetic', frameId: 'frame-a', frameName: 'Frame A', finalImage: jpeg, photos: [{ id: 'photo-a', dataUrl: jpeg }] })
  await drive.processQueue()
  assert.equal(calls.filter(call => call.method === 'POST' && call.url.includes('upload')).length, 3, 'Existing files should be updated, not duplicated')
  assert.ok(calls.some(call => call.method === 'DELETE' && call.url.endsWith(`/${initialFiles['photo-b']}`)), 'Removed photo should be removed from shared folder')
  assert.equal(calls.filter(call => call.url.includes('/permissions')).length, 1, 'Retry should not create a second permission')
  const statePath = join(root, 'state.json')
  const state = JSON.parse(await readFile(statePath, 'utf8'))
  state.sessions['session-a'].frames['frame-a'].expiresAt = new Date(Date.now() - 1000).toISOString()
  await writeFile(statePath, JSON.stringify(state))
  await drive.cleanupExpired()
  assert.equal(await drive.frameLink('session-a', 'frame-a'), null)
  assert.ok(calls.some(call => call.method === 'DELETE' && call.url.includes('/permissions/')), 'Expiry should revoke the public permission')
  assert.ok(calls.some(call => call.method === 'PATCH' && call.url.endsWith('/created-3')), 'Expiry should trash only the app-created frame folder')
  await drive.queueFrame({ sessionId: 'session-a', sessionName: 'Synthetic', frameId: 'frame-b', frameName: 'Frame B', finalImage: jpeg, photos: [{ id: 'photo-c', dataUrl: jpeg }] })
  await drive.processQueue()
  const second = await drive.frameLink('session-a', 'frame-b')
  assert.ok(second)
  await drive.queueDriveDeletion('session-a', 'frame-b')
  await drive.processQueue()
  assert.equal(await drive.frameLink('session-a', 'frame-b'), null)
  assert.ok(calls.some(call => call.method === 'PATCH' && call.url.endsWith(second.url.split('/').pop())), 'Deleting a local frame should trash its Drive folder')
  // Simulate a migrated state file that lost the root ID: discovery must reuse
  // the existing app-visible Drive folder instead of creating a duplicate.
  const migrated = JSON.parse(await readFile(statePath, 'utf8'))
  delete migrated.rootFolderId
  await writeFile(statePath, JSON.stringify(migrated))
  await drive.queueFrame({ sessionId: 'session-b', sessionName: 'Synthetic 2', frameId: 'frame-c', frameName: 'Frame C', finalImage: jpeg, photos: [{ id: 'photo-d', dataUrl: jpeg }] })
  await drive.processQueue()
  const secondSession = JSON.parse(await readFile(statePath, 'utf8')).sessions['session-b']
  assert.equal(JSON.parse(calls.filter(call => call.method === 'POST' && call.url.startsWith('https://www.googleapis.com/drive/v3/files?')).at(-2).body).parents[0], 'created-1', 'Later sessions must reuse the same root')
  await drive.queueDriveDeletion('session-b')
  await drive.processQueue()
  assert.equal(await drive.sessionFolder('session-b'), null)
  assert.ok(calls.some(call => call.method === 'PATCH' && call.url.endsWith(`/${secondSession.folderId}`)), 'Deleting a local session should trash its private parent')
  const rootCreates = calls.filter(call => call.method === 'POST' && call.url.startsWith('https://www.googleapis.com/drive/v3/files?') && JSON.parse(call.body).name === 'LUMA Booth')
  assert.equal(rootCreates.length, 1, 'Multiple sessions must not create duplicate root folders')
  await drive.queueFrame({ sessionId: 'session-c', sessionName: 'Synthetic 3', frameId: 'frame-d', frameName: 'Frame D', finalImage: jpeg, photos: [{ id: 'photo-e', dataUrl: jpeg }], shareFrame: false })
  await drive.processQueue()
  assert.equal(await drive.frameLink('session-c', 'frame-d'), null, 'Session upload must not publish an individual frame QR')
  await drive.setSessionSharing('session-c', true)
  const sessionQr = await drive.sessionLink('session-c')
  assert.ok(sessionQr?.url.includes('/folders/'), 'Session QR must link to its folder')
  assert.ok(await drive.frameLink('session-c', 'frame-d'), 'Frame QR must work through session permission')
  const sharedSessionFolderId = sessionQr.url.split('/').pop()
  await drive.setSessionSharing('session-c', false)
  assert.equal(await drive.sessionLink('session-c'), null, 'Disabling session QR must revoke its link')
  assert.equal(await drive.frameLink('session-c', 'frame-d'), null, 'Disabling session QR must revoke inherited frame access')
  await drive.setSessionSharing('session-c', true)
  const expiring = JSON.parse(await readFile(statePath, 'utf8'))
  expiring.sessions['session-c'].expiresAt = new Date(Date.now() - 1000).toISOString()
  await writeFile(statePath, JSON.stringify(expiring))
  await drive.cleanupExpired()
  assert.equal(await drive.sessionLink('session-c'), null, 'Expired session QR must be revoked')
  const sessionPermissions = calls.filter(call => call.url.includes(`/${sharedSessionFolderId}/permissions`))
  assert.ok(sessionPermissions.some(call => call.method === 'DELETE'), 'Session permission must be removed')
  const preparedUrl = await drive.prepareFrameShare({ sessionId: 'session-d', sessionName: 'Synthetic 4', frameId: 'frame-e', frameName: 'Frame E', shareFrame: true })
  assert.match(preparedUrl, /^https:\/\/drive\.google\.com\/drive\/folders\/created-/)
  assert.equal((await drive.frameLink('session-d', 'frame-e')).url, preparedUrl, 'Prepare must expose a real QR URL before rendering the final JPEG')
  await drive.queueFrame({ sessionId: 'session-d', sessionName: 'Synthetic 4', frameId: 'frame-e', frameName: 'Frame E', finalImage: jpeg, photos: [{ id: 'photo-f', dataUrl: jpeg }], shareFrame: true })
  await drive.processQueue()
  assert.equal((await drive.frameLink('session-d', 'frame-e')).url, preparedUrl, 'Uploading must reuse the prepared folder')
  console.log('PASS single Drive root, folder nesting, offline queue, isolation, updates, expiry, frame/session deletion, session QR, prepared frame QR')
}

app.whenReady().then(main).then(() => app.quit()).catch(error => { console.error(error); process.exit(1) })
